export const runtime = 'nodejs'

import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import { gateway } from '@/lib/x402'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ fingerprint: string }> }
) {
  const { fingerprint } = await params

  console.log('[cite] SELLER_ADDRESS:', process.env.SELLER_ADDRESS)
  console.log('[cite] facilitatorUrl: https://gateway-api-testnet.circle.com')
  console.log('[cite] PAYMENT-SIGNATURE header present:', !!request.headers.get('payment-signature'))
  console.log('[cite] PAYMENT-SIGNATURE value (first 50 chars):', request.headers.get('payment-signature')?.slice(0, 50))

  // 1. Look up the article by fingerprint
  const { data: article, error } = await supabaseAdmin
    .from('articles')
    .select('*, publishers(name, slug, wallet_address)')
    .eq('content_fingerprint', fingerprint)
    .single()

  if (error || !article) {
    return NextResponse.json({ error: 'Article not found' }, { status: 404 })
  }

  // 2. Apply x402 payment gate
  const priceUsdc = article.price_usdc || 0.001
  
  // Create Express-like mocks to run the GatewayMiddleware inside Next App Router
  const reqMock = {
    headers: Object.fromEntries(request.headers.entries()),
    url: request.url,
  } as any;
  
  let statusCode = 200;
  let headersToSet: Record<string, string> = {};
  let bodyData: any = null;
  let hasEnded = false;
  
  const resMock = {
    setHeader: (name: string, value: string) => { headersToSet[name] = value },
    end: (data: string) => { bodyData = data; hasEnded = true; },
    set statusCode(code: number) { statusCode = code; }
  } as any;
  
  const mw = gateway.require(`$${priceUsdc}`);
  
  // Run the middleware and wait for either next() or res.end()
  const middlewareRanToNext = await new Promise<boolean>((resolve) => {
    resMock.end = (data: string) => { 
      bodyData = data; 
      hasEnded = true; 
      resolve(false); 
    };
    
    Promise.resolve(mw(reqMock, resMock, (err?: any) => {
      if (err) {
        statusCode = 500;
        bodyData = JSON.stringify({ error: 'Middleware error', message: err.message });
        resolve(false);
      } else {
        resolve(true); // next() was called, payment verified
      }
    })).catch((err: any) => {
      statusCode = 500;
      bodyData = JSON.stringify({ error: 'Middleware error', message: err.message });
      resolve(false);
    });
  });

  if (!middlewareRanToNext) {
    // Return the 402 (or 500/400) generated by the gateway middleware
    return new NextResponse(bodyData, {
      status: statusCode,
      headers: headersToSet
    });
  }

  // 3. Payment verified — log to database
  const payerAddress = reqMock.payment?.payer || 'unknown'
  const txHash = reqMock.payment?.transaction || null
  
  await supabaseAdmin.from('citation_payments').insert({
    article_id: article.id,
    publisher_id: article.publisher_id,
    payer_address: payerAddress,
    amount_usdc: priceUsdc,
    arc_tx_hash: txHash,
  })

  // 4. Update counters
  await supabaseAdmin.from('articles')
    .update({ 
      citation_count: article.citation_count + 1,
      total_earned_usdc: Number(article.total_earned_usdc) + priceUsdc
    })
    .eq('id', article.id)

  const publisherRecord = article.publishers as any
  await supabaseAdmin.from('publishers')
    .update({
      citation_count: publisherRecord.citation_count + 1,
      total_earned_usdc: Number(publisherRecord.total_earned_usdc) + priceUsdc
    })
    .eq('id', article.publisher_id)

  // 5. Return citable content
  return NextResponse.json({
    title: article.title,
    url: article.url,
    publisher: publisherRecord?.name,
    publisher_slug: publisherRecord?.slug,
    fingerprint: fingerprint,
    price_paid_usdc: priceUsdc,
    cite_as: `${article.title} — ${article.url}`,
  })
}

export async function OPTIONS(request: NextRequest) {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, payment-signature, x-payment-signature, x-payment-address',
      'Access-Control-Expose-Headers': 'PAYMENT-REQUIRED, PAYMENT-RESPONSE',
    },
  });
}
